name: 'Update Repository Settings'
description: 'Read a config.yml file and update settings for a github repository'
inputs:
  repo-token:
    description: 'github token'
runs:
  using: 'node20'
  main: 'index.js'
